---
- hosts: localhost
  gather_facts: false

  vars_files:
    - vars/prod/main.yml

  tasks:
    - name: Deploy wordpress secrets
      k8s:
        definition: "{{ item }}"
        kubeconfig: "{{ k8s_kubeconfig }}"
        state: "{{ deploy_k8s_state }}"
      loop: "{{ lookup('template', 'tasks/mysql-pass.yml') | from_yaml_all | list }}"
      no_log: false

    - name: Deploy MySQL and wordpress
      k8s:
        definition: "{{ item }}"
        kubeconfig: "{{ k8s_kubeconfig }}"
        state: "{{ deploy_k8s_state }}"
      loop:
        - "{{ lookup('template', 'tasks/mysql.yml') | from_yaml_all | list }}"
        - "{{ lookup('template', 'tasks/wordpress.yml') | from_yaml_all | list }}"

    - name: Get Load balancer dns name
      k8s_info:
        kubeconfig: "{{ k8s_kubeconfig }}"
        kind: Service
        name: wordpress
        namespace: default
      register: wordpress_svc
      when:
        - deploy_k8s_state == "present"
        - aws_environment | bool

    - name: set loadbalancer url as fact
      set_fact:
        wordpress_lb_host: "{{ wordpress_svc['resources'][0]['status']['loadBalancer']['ingress'][0]['hostname'] }}"
      when:
        - deploy_k8s_state == "present"
        - aws_environment | bool

    - name: wait for load balancer to respond
      uri:
        url: "https://{{ wordpress_lb_host }}"
        validate_certs: false
      register: lb_result
      until: lb_result.status == 200
      retries: 60
      delay: 5
      when:
        - deploy_k8s_state == "present"
        - aws_environment | bool

    - name: get ELB info
      ec2_elb_info:
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
        names: "{{ wordpress_lb_host.split('-')[0] }}"
      register: elb_info
      when:
        - deploy_k8s_state == "present"
        - aws_environment | bool

    - name: Add an A record in route53
      route53:
        profile: "{{ aws_profile }}"
        zone: "{{ wordpress_route53_zone }}"
        record: "{{ wordpress_route53_domain }}"
        state: "{{ deploy_k8s_state }}"
        type: A
        ttl: 300
        value: '{{ wordpress_lb_host }}'
        alias: true
        alias_hosted_zone_id: "{{ elb_info['elbs'][0]['canonical_hosted_zone_name_id'] }}"
      register: result
      ignore_errors: true
      when:
        - deploy_k8s_state == "present"
        - aws_environment | bool

    # - name: Test SSL connection
    #   uri:
    #     url: "https://{{ wordpress_route53_domain }}"
    #   register: ssl_status
    #   when:
    #     - deploy_k8s_state == "present"
    #     - aws_environment | bool